Add: urls.py / validation.py / views.py
wecode-bootcamp-korea/34-backend-westagram-2 pull request #7
Opened 2022-06-13 06:04 UTC by HyeonWooJo

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 회원가입 구현
		 
## 수정 사항들 자세한 내용
1) 회원가입 기능 추가
- 성, 이름, 유저이름, 이메일, 패스워드, 전화번호를 받아서 DB에 저장
2) 이메일, 패스워드 유효성 추가
- 이메일: @과 . 필수로 작성 하도록 조건 추가
- 패스워드: 8자이상, 문자, 숫자, 특수문자의 복합 조건 추가

## 기타 질문 및 특이 사항
- 없음

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-06-13 07:31 UTC, Kang-kyunghun requested changes

2022-06-13 07:31 UTC, Kang-kyunghun commented on students/hyeonwoo/users/views.py
> +from .models            import User
1. 사용 안 하는 package는 제거해 주세요.
2. import 는 크게 3가지로 구분 지어서 작성합니다.
- 파이썬 내장 package
- pip 로 설치한 외부 package
- 프로젝트 내에 작성한 package

```suggestion
import json

from django.core.exceptions import ValidationError
from django.http            import JsonResponse
from django.views           import View

from .validation import validation_email, validation_password
from .models     import User
```

2022-06-13 07:31 UTC, Kang-kyunghun commented on students/hyeonwoo/users/views.py
> +
불필요한 코드는 제거하고 올려주세요.

2022-06-13 07:31 UTC, Kang-kyunghun commented on students/hyeonwoo/users/views.py
> +            first_name    = data['first_name']
data도 try문 안으로 넣어 주세요.
```suggestion
        try :
            data = json.loads(request.body)
            first_name    = data['first_name']
```

2022-06-13 07:32 UTC, Kang-kyunghun commented
PR 제목 형식에 맞게 수정해 주세요.

2022-06-13 07:39 UTC, HyeonWooJo commented on students/hyeonwoo/users/views.py
> +            first_name    = data['first_name']
네 알겠습니다. 수정 후 다시 PR 하도록 하겠습니다.

2022-06-13 08:25 UTC, HyeonWooJo commented
>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 회원가입 구현
		 
## 수정 사항들 자세한 내용
1) 이메일, 패스워드 유효성 추가(validation.py)
- 이메일, 패스워드를 빈 값으로 받을 때 DB에  ""로 받는 오류가 있어 해당 오류 수정


## 기타 질문 및 특이 사항
- 없음

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-06-14 01:11 UTC, Kang-kyunghun requested changes

2022-06-14 01:11 UTC, Kang-kyunghun commented on students/hyeonwoo/users/models.py
> +    mobile_number = models.CharField(max_length=45, blank=False)
blanke = False을 사용한 이유를 코멘트로 남겨주세요.

2022-06-14 01:11 UTC, Kang-kyunghun commented on students/hyeonwoo/users/validation.py
> +        raise ValidationError('NO_VALUE')
값이 아예 없을 때를 의미 하나요? 
그렇다면 첫번째 정규 표현식으로도 잡을 수 있지 않을까요? 테스트 한 번 해보시고 알려주세요.

2022-06-14 01:11 UTC, Kang-kyunghun commented on students/hyeonwoo/users/validation.py
> +        raise ValidationError('NO_VALUE')
이 부분도 마찬가지 입니다.

2022-06-14 01:11 UTC, Kang-kyunghun commented on students/hyeonwoo/westagram/urls.py
> +    path('westagram', include('users.urls'))
```suggestion
    path('users', include('users.urls'))
```

2022-06-14 01:21 UTC, HyeonWooJo commented on students/hyeonwoo/users/validation.py
> +        raise ValidationError('NO_VALUE')
원래 했을 때는 안 잡혔는데 다시 해보니 테스트 해보니 잘 잡혀서 기존 정규표현식으로 수정 하겠습니다.

2022-06-14 01:22 UTC, HyeonWooJo commented on students/hyeonwoo/users/validation.py
> +        raise ValidationError('NO_VALUE')
기존 정규표현식으로 수정하겠습니다.

2022-06-14 02:39 UTC, HyeonWooJo commented
models.py의  blank=False 부분은 POST시 빈 값을 주었을 때 DB에 빈 값이 그대로 저장되는 것을 방지하고자 넣었습니다. 초반에는 정규표현식으로도 이것이 해결되지 않아 blank=False로 해결해보려고 하였으나 이것으로도 해결되지 않았습니다. 현재는 정규표현식으로 해결되어 blank=False 부분 모두 없애고 다시 push 하였습니다.

2022-06-14 04:55 UTC, merged

2022-06-14 04:56 UTC, Kang-kyunghun commented
LGTM~!